# Base image
FROM python:3.9.7-slim-buster

# Set working directory
WORKDIR /app

# Copy requirements.txt file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY . .

# Start the application
CMD ["python", "Logistic_Regression_with_a_Neural_Network_mindset.ipynb"]